# 2.2 数据操作

In [1]:
import torch

torch.manual_seed(0)
torch.cuda.manual_seed(0)
print(torch.__version__)

2.3.1+cpu


## 2.2.1 创建`Tensor`

创建一个5x3的未初始化的`Tensor`：

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[-4.6593e-10,  7.5110e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


创建一个5x3的随机初始化的`Tensor`:



In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341],
        [0.4901, 0.8964, 0.4556],
        [0.6323, 0.3489, 0.4017],
        [0.0223, 0.1689, 0.2939]])


创建一个5x3的long型全0的`Tensor`:



In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


直接根据数据创建:

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


还可以通过现有的`Tensor`来创建，此方法会默认重用输入`Tensor`的一些属性，例如数据类型，除非自定义数据类型。

In [6]:
x = x.new_ones(5, 3, dtype=torch.float64)      # 返回的tensor默认具有相同的torch.dtype和torch.device
print(x)

x = torch.randn_like(x, dtype=torch.float)    # 指定新的数据类型
print(x)                                    

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.6035,  0.8110, -0.0451],
        [ 0.8797,  1.0482, -0.0445],
        [-0.7229,  2.8663, -0.5655],
        [ 0.1604, -0.0254,  1.0739],
        [ 2.2628, -0.9175, -0.2251]])


我们可以通过`shape`或者`size()`来获取`Tensor`的形状:

In [7]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


> 注意：返回的torch.Size其实就是一个tuple, 支持所有tuple的操作。

## 2.2.2 操作
### 算术操作
* **加法形式一**

In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.3967,  1.0892,  0.4369],
        [ 1.6995,  2.0453,  0.6539],
        [-0.1553,  3.7016, -0.3599],
        [ 0.7536,  0.0870,  1.2274],
        [ 2.5046, -0.1913,  0.4760]])


* **加法形式二**

In [9]:
print(torch.add(x, y))

tensor([[ 1.3967,  1.0892,  0.4369],
        [ 1.6995,  2.0453,  0.6539],
        [-0.1553,  3.7016, -0.3599],
        [ 0.7536,  0.0870,  1.2274],
        [ 2.5046, -0.1913,  0.4760]])


In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.3967,  1.0892,  0.4369],
        [ 1.6995,  2.0453,  0.6539],
        [-0.1553,  3.7016, -0.3599],
        [ 0.7536,  0.0870,  1.2274],
        [ 2.5046, -0.1913,  0.4760]])


* **加法形式三、inplace**

In [11]:
# adds x to y
y.add_(x)   # 任何in-place改变张量的操作后面都固定一个_。例如x.copy_(y)、x.t_()将更改x
# y += x
print(y)

tensor([[ 1.3967,  1.0892,  0.4369],
        [ 1.6995,  2.0453,  0.6539],
        [-0.1553,  3.7016, -0.3599],
        [ 0.7536,  0.0870,  1.2274],
        [ 2.5046, -0.1913,  0.4760]])


> **注：PyTorch操作inplace版本都有后缀"_", 例如`x.copy_(y), x.t_()`**

### 索引
我们还可以使用类似NumPy的索引操作来访问`Tensor`的一部分，需要注意的是：**索引出来的结果与原数据共享内存，也即修改一个，另一个会跟着修改。** 

In [44]:
x=torch.tensor([[1,2,3],[4,5,6]])
y = x[0, :]
print(y)
y += 1
print(y)
print(x) # 源tensor也被改了
x+=1
print(x)
print(y)

tensor([1, 2, 3])
tensor([2, 3, 4])
tensor([[2, 3, 4],
        [4, 5, 6]])
tensor([[3, 4, 5],
        [5, 6, 7]])
tensor([3, 4, 5])


### 改变形状
用`view()`来改变`Tensor`的形状：

In [53]:
x = torch.randint(10, (3, 2, 4))
y = x.view(2, 12)

z = x.view(-1, 1, 4)  # -1所指的维度可以根据其他维度的值推出来

print(x.size(), y.size(), z.size())
# print(x)
# print(y)
# print(z)

torch.Size([3, 2, 4]) torch.Size([2, 12]) torch.Size([6, 1, 4])


**注意`view()`返回的新tensor与源tensor共享内存，也即更改其中的一个，另外一个也会跟着改变。**

In [14]:
x += 1
print(x)
print(y) # 也加了1

tensor([[2.6035, 2.8110, 1.9549],
        [1.8797, 2.0482, 0.9555],
        [0.2771, 3.8663, 0.4345],
        [1.1604, 0.9746, 2.0739],
        [3.2628, 0.0825, 0.7749]])
tensor([2.6035, 2.8110, 1.9549, 1.8797, 2.0482, 0.9555, 0.2771, 3.8663, 0.4345,
        1.1604, 0.9746, 2.0739, 3.2628, 0.0825, 0.7749])


如果不想共享内存，推荐先用`clone`创造一个副本然后再使用`view`。

In [15]:
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[ 1.6035,  1.8110,  0.9549],
        [ 0.8797,  1.0482, -0.0445],
        [-0.7229,  2.8663, -0.5655],
        [ 0.1604, -0.0254,  1.0739],
        [ 2.2628, -0.9175, -0.2251]])
tensor([2.6035, 2.8110, 1.9549, 1.8797, 2.0482, 0.9555, 0.2771, 3.8663, 0.4345,
        1.1604, 0.9746, 2.0739, 3.2628, 0.0825, 0.7749])


另外一个常用的函数就是`item()`, 它可以将一个标量`Tensor`转换成一个Python number：

In [56]:
x = torch.randn(2, 3)
print(x)
print(x[0,0].item())

tensor([[ 0.4141, -0.8632,  0.7942],
        [-1.1814, -0.5982,  0.9610]])
0.41414621472358704


In [ ]:
x=torch.randint(10, (3, 3))
print(x)
# print(x.trace())    # 迹，对角线元素之和
# print(x.t())        # 转置
# print(x.diag())     # 对角线元素
# print(x.triu(diagonal=1))    # 上三角矩阵
# print(x.tril(diagonal=1))    # 下三角矩阵

y=torch.randint(5, (3, 3))
print(y)
# print(x.mm(y))  # 矩阵乘法，等价于torch.matmul(x, y)和x @ y
# print(x.addmm(x,y)) # 等价于x + torch.mm(x, y)
# print(x.mul(y)) # 对应元素相乘，等价于torch.mul(x, y)和x * y
# print(x.div(y)) # 对应元素相除，等价于torch.div(x, y)和x / y
# print(x.pow(2)) # 指数运算，等价于torch.pow(x, 2)和x ** 2
# print(x.sqrt()) # 开方，等价于torch.sqrt(x)
# print(x.exp()) # 指数运算，等价于torch.exp(x)
# print(x.log()) # 对数运算，等价于torch.log(x)
# print(x.abs()) # 绝对值，等价于torch.abs(x)

# x1,y1=torch.tensor([1,2,3]),torch.tensor([4,5,6])
# print(x1.dot(y1)) # 内积，只能对1维tensor进行计算，等价于torch.dot(x, y)
# print(x1.cross(y1)) # 叉积，只能对3维tensor进行计算，等价于torch.cross(x, y)

# z=torch.rand(3, 3)
# print(z)
# print(z.inverse()) # 逆矩阵
# print(z.svd()) # 奇异值分解


tensor([[6, 9, 8],
        [5, 6, 7],
        [7, 2, 3]])
tensor([[0, 0, 3],
        [1, 2, 1],
        [3, 3, 0]])
tensor([[0.1661, 0.5328, 0.0285],
        [0.4297, 0.1771, 0.1534],
        [0.6965, 0.1152, 0.1211]])
tensor([[ 1.3662e-01, -2.2089e+00,  2.7659e+00],
        [ 1.9770e+00,  9.2248e-03, -4.7726e-01],
        [-2.6661e+00,  1.2698e+01, -7.1980e+00]])
torch.return_types.svd(
U=tensor([[-0.4139,  0.8935,  0.1741],
        [-0.5252, -0.0782, -0.8474],
        [-0.7435, -0.4421,  0.5017]]),
S=tensor([0.9233, 0.4561, 0.0658]),
V=tensor([[-0.8798, -0.4234,  0.2161],
        [-0.4323,  0.9017,  0.0064],
        [-0.1975, -0.0878, -0.9764]]))


## 2.2.3 广播机制

In [95]:
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)
print(torch.tensor([1,1]) + torch.tensor([[1],[1]]))

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])
tensor([[2, 2],
        [2, 2]])


## 2.2.4 运算的内存开销

In [18]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y + x
print(id(y) == id_before)

False


In [19]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
print(id(y) == id_before)

True


In [20]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y) # y += x, y.add_(x)
print(id(y) == id_before)

True


In [97]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
z=y.view(-1,2)
print(id(z) == id_before)   # 虽然view返回的Tensor与源Tensor是共享data的，但是依然是一个新的Tensor（因为Tensor除了包含data外还有一些其他属性），二者id（内存地址）并不一致。

False


## 2.2.5 `Tensor`和NumPy相互转换
**`numpy()`和`from_numpy()`这两个函数产生的`Tensor`和NumPy array实际是使用的相同的内存，改变其中一个时另一个也会改变！！！**
### `Tensor`转NumPy

In [21]:
a = torch.ones(5)
b = a.numpy()
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


### NumPy数组转`Tensor`

In [22]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


直接用`torch.tensor()`将NumPy数组转换成`Tensor`，该方法总是会进行数据拷贝，返回的`Tensor`和原来的数据不再共享内存。

In [23]:
# 用torch.tensor()转换时不会共享内存
c = torch.tensor(a)
a += 1
print(a, c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


## 2.2.6 `Tensor` on GPU

In [98]:
# 以下代码只有在PyTorch GPU版本上才会执行
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # 直接创建一个在GPU上的Tensor
    x = x.to(device)                       # 等价于 .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to()还可以同时更改数据类型